version: '3.8'

services:
  app:
    build: .
    container_name: videos-api
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./srv:/srv
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: videos-db
    environment:
      POSTGRES_DB: ab_api
      POSTGRES_USER: oliverdev
      POSTGRES_PASSWORD: Senha123$
    ports:
      - "5432:5432"
