spring:
  datasource:
    url: jdbc:postgresql://db.ozidmttuoymngufcnjsx.supabase.co:5432/postgres
    username: postgres
    password: Joao2022%
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

supabase:
  bucket-url: https://ozidmttuoymngufcnjsx.supabase.co/storage/v1/object/public/videos//
